### ISSUE TITLE
Angular is not defined

### ISSUE THREAD

**Issue by onelifemedia** [henyojess/generator-gulp-ng#3]
I looked in index.html, and noticed that there's no reference to angular.js.  Did you want a pull request for this?

**Comment by henyojess** [comment]
angularjs and other vendor libraries will be combined into lib.js which is loaded by index.html

**Comment by horak** [comment]
Yeah but it's still throwing the "Angular is not defined" error, which is odd since lib does include angular...
![4ee5774b56e21932cf1c9c0abdd77df1](https://cloud.githubusercontent.com/assets/1111424/2871363/b1462cea-d306-11e3-971a-a6e72b418dc8.png)

**Comment by lukebrooker** [comment]
Seems like it just needs a better jshint config

**Comment by CYBAI** [comment]
I also got the same issue of jshint. I also try to re-savedev to the config, but it still got errors.

**Comment by niallobrien** [comment]
Fresh install. Same errors.

**Comment by ee99ee** [comment]
Also seeing the same errors

**Comment by henyojess** [comment]
working on this isssue. currently installing node v0.10.28 then will start with a fresh install

**Comment by henyojess** [comment]
fixed has been committed and package version bumped to 1.0.2

**Comment by ee99ee** [comment]
How does one update an existing project with whatever changes are applied in this fix?

**Comment by DigitalMachinist** [comment]
@ee99ee:
You can specify angular as a global in your .jshintrc file with the line:

```
"predef": [ "angular" ]
```

or theoretically inline in your angular-dependent files with:

```
/* global angular: false */
```

although, I have not attempted the latter.

**Comment by ee99ee** [comment]
Nice that did it... thanks! Still getting this error, though:

```
/path/to/my/app/admin/app/app.js: line 1, col 1, Use the function form of "use strict".

1 error
/path/to/my/app/admin/app/main/main_controller.js: line 1, col 1, Use the function form of "use strict".

1 error
```

**Comment by DigitalMachinist** [comment]
Try changing your app.js and main_controller.js so that they have "use strict"; as the first line inside the top-level function call, like so:

```
( function () {
  'use strict';
  // angular module or controller definition goes here
} )();
```

**Comment by ee99ee** [comment]
That fixed it!

**Comment by creunabo** [comment]
"unused": true,
  "strict": true,
  "jquery": true,
  "globals": {
    "angular": false,
    "$": false
  }

add a globals sections, this can ensure jshint to ignore global entities like jquery's prefix'er and angular and so on
